### ISSUE TITLE
Numbered headings via CSS

### ISSUE THREAD

**Issue by arnaud-m** [arnaud-m/master-info#59]
[Source](https://2ality.com/2012/01/numbering-headingshtml.html).
For instance, let add number to the TER subjects. 
```css
<style>
body {counter-reset:section;}

h3:before
{
    counter-increment:section;
    content:counter(section) ". ";
}
</style>
```
